wildMagic = {
    1: 'Roll on this table at the start of each of your turns for the next minute, ignoring this result on subsequent rolls.',
    2: 'For the next minute, you can see any invisible creature if you have line of sight to it.',
    3: 'A modron chosen and controlled by the DM appears in an unoccupied space within 5 feet of you, then disappears 1 minute later.',
    4: 'You cast fireball as a 3rd-level spell centered on yourself.',
    5: 'You cast magic missile as a 5th-level spell.',
    6: 'Roll a d10. Your height changes by a number of inches equal to the roll. If the roll is odd, you shrink. If the roll is even, you grow.',
    7: 'You cast confusion centered on yourself.',
    8: 'For the next minute, you regain 5 hit points at the start of each of your turns.',
    9: 'You grow a long beard made of feathers that remains until you sneeze, at which point the feathers explode out from your face.',
    10: 'You cast grease centered on yourself.',
    11: 'Creatures have disadvantage on saving throws against the next spell you cast in the next minute that involves a saving throw.',
    12: 'Your skin turns a vibrant shade of blue. A remove curse spell can end this effect.',
    13: 'An eye appears on your forehead for the next minute. During that time, you have advantage on Wisdom (Perception) checks that rely on sight.',
    14: 'For the next minute, all your spells with a casting time of 1 action have a casting time of 1 bonus action.',
    15: 'You teleport up to 60 feet to an unoccupied space of your choice that you can see.',
    16: 'You are transported to the Astral Plane until the end of your next turn, after which time you return to the space you previously occupied or the nearest unoccupied space if that space is occupied.',
    17: 'Maximize the damage of the next damaging spell you cast within the next minute.',
    18: 'Roll a d10. Your age changes by a number of years equal to the roll. If the roll is odd, you get younger (minimum 1 year old). If the roll is even, you get older.',
    19: '1d6 flumphs controlled by the DM appear in unoccupied spaces within 60 feet of you and are frightened of you. They vanish after 1 minute.',
    20: 'You regain 2d10 hit points.',
    21: 'You turn into a potted plant until the start of your next turn. While a plant, you are incapacitated and have vulnerability to all damage. If you drop to 0 hit points, your pot breaks, and your form reverts.',
    22: 'For the next minute, you can teleport up to 20 feet as a bonus action on each of your turns.',
    23: 'You cast levitate on yourself.',
    24: 'A unicorn controlled by the DM appears in a space within 5 feet of you, then disappears 1 minute later.',
    25: 'You can’t speak for the next minute. Whenever you try, pink bubbles float out of your mouth.',
    26: 'A spectral shield hovers near you for the next minute, granting you a +2 bonus to AC and immunity to magic missile.',
    27: 'You are immune to being intoxicated by alcohol for the next 5d6 days.',
    28: 'Your hair falls out but grows back within 24 hours.',
    29: 'For the next minute, any flammable object you touch that isn’t being worn or carried by another creature bursts into flame.',
    30: 'You regain your lowest-level expended spell slot.',
    31: 'For the next minute, you must shout when you speak.',
    32: 'You cast fog cloud centered on yourself.',
    33: 'Up to three creatures you choose within 30 feet of you take 4d10 lightning damage.',
    34: 'You are frightened by the nearest creature until the end of your next turn.',
    35: 'Each creature within 30 feet of you becomes invisible for the next minute. The invisibility ends on a creature when it attacks or casts a spell.',
    36: 'You gain resistance to all damage for the next minute.',
    37: 'A random creature within 60 feet of you becomes poisoned for 1d4 hours.',
    38: 'You glow with bright light in a 30-foot radius for the next minute. Any creature that ends its turn within 5 feet of you is blinded until the end of its next turn.',
    39: 'You cast polymorph on yourself. If you fail the saving throw, you turn into a sheep for the spell’s duration.',
    40: 'Illusory butterflies and flower petals flutter in the air within 10 feet of you for the next minute.',
    41: 'You can take one additional action immediately.',
    42: 'Each creature within 30 feet of you takes 1d10 necrotic damage. You regain hit points equal to the sum of the necrotic damage dealt.',
    43: 'You cast mirror image.',
    44: 'You cast fly on a random creature within 60 feet of you.',
    45: 'You become invisible for the next minute. During that time, other creatures can’t hear you. The invisibility ends if you attack or cast a spell.',
    46: 'If you die within the next minute, you immediately come back to life as if by the reincarnate spell.',
    47: 'Your size increases by one size category for the next minute.',
    48: 'You and all creatures within 30 feet of you gain vulnerability to piercing damage for the next minute.',
    49: 'You are surrounded by faint, ethereal music for the next minute.',
    50: 'You regain all expended sorcery points.',
}